world:
  grid_width: 51
  grid_height: 51
  start_pos: [25, 25]
  rng_seed: 45

viz:
  fps: 4

food:
  feeding_paradigm: only_initial
  initial_fraction_per_cell: 0.5

worm:
  worm_version: random
  speed: 1
  energy_capacity: 20
  metabolic_rate: 1
