world:
  grid_width: 51
  grid_height: 51
  start_pos:
  - 26
  - 26
  rng_seed: 47
viz:
  enabled: false
  fps: 4
food:
  feeding_paradigm:
    initial: true
    regrow: true
  initial_fraction_per_cell: 0.1
  regrow_time: 30
worm:
  speed: 1
  energy_capacity: 30
  metabolic_rate: 1
sensors:
  active:
  - current_field
  - adjacent_binary
decisionmaking:
  version: adjacent_food
  brain: false
