world:
  grid_width: 51
  grid_height: 51
  start_pos:
  - 26
  - 26
  rng_seed: 1
viz:
  enabled: true
  fps: 1.0
  brain_enabled: true
  brain_fps: 2.0
food:
  feeding_paradigm:
    initial: true
    regrow: true
  initial_fraction_per_cell: 0.1
  regrow_time: 30
worm:
  speed: 1
  energy_capacity: 30
  metabolic_rate: 1
sensors:
  active:
  - current_field
  - adjacent_binary
decisionmaking:
  version: neuronal_algorithm
  brain:
    init: prio_food
    max_delay_decision: 2.0

